### PR TITLE
Move Media About Morphir panel to Morphir Homepage

### PR DESCRIPTION
**Pull request by ronaldssebalamu**
Moved the Media About Morphir panel to the Morphir Homepage.
Deleted the Media.md file from the docusaurus microsite.

The deploy preview on Netlify can be found here 👉🏻 https://deploy-preview-187--angry-raman-7c44f6.netlify.app/

### CODE REVIEW

**Comment by mcleo-d** [comment]
This PR replaces https://github.com/finos/morphir/pull/157

**Comment by mcleo-d** [comment]
Congratulations @ronaldssebalamu for raising your first CLA approved pull request to FINOS.

**Comment by mcleo-d** [comment]
Hi @stephengoldbaum and @AttilaMihaly,

Do you mind reviewing this PR and giving feedback if required.

Thank you.

James.

cc @ronaldssebalamu

**Comment by mcleo-d** [comment]
Hi @AttilaMihaly - Do you mind merging this pull request as we're running the risk of merge conflicts as it's been open for a while.

Many thanks,

James.

**Review by stephengoldbaum — APPROVED** [review]

**Comment by stephengoldbaum** [comment]
Merged

**Pull request merged**
